todo/config/routes.rb
Rails.application.routes.draw do

  root 'lists#index'

  resources :lists do
    resources :tasks
  end

end

todo/app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  validates :name, presence: true, uniqueness: true
end

todo/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

end

todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

todo/app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.order(:id)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.create(list_params)
    redirect_to lists_path
  end

  # def show
  #   #pass in all the tasks for the list
  #   @list = List.find_by(id: params[:id])
  # end

  def edit
    @list = List.find_by(id: params[:id])
  end

  def update
    List.update(params[:id], list_params)
    redirect_to lists_path
  end

  def destroy
    List.destroy(params[:id])
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @list = List.find_by(id: params[:list_id])
  end

  def new
    @task = Task.new
    @list = List.find_by(id: params[:list_id])
  end

  def create
    task = Task.new(task_params)
    list = List.find_by(id: params[:list_id]).tasks << task
    task.save
    redirect_to list_tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title)
  end

end

todo/app/helpers/application_helper.rb
module ApplicationHelper
end

todo/app/helpers/lists_helper.rb
module ListsHelper
end

todo/app/helpers/tasks_helper.rb
module TasksHelper
end

todo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todo/app/views/lists/_form.erb
<%= form_for list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name , value: list.name %>
  <%= f.submit %>
<%end%>

todo/app/views/lists/edit.erb
<h3>Edit</h3>

<%= render partial: 'form', locals: {list: @list}%>

todo/app/views/lists/index.erb
<h1>Welcome to ToDo</h1>
<% @lists.each do |list| %>
  <a href="<%= list_tasks_path(list.id) %>"><%= list.name %></a>
  <br>
  <a href="<%= edit_list_path(list.id) %>">Edit</a>
  <%= link_to 'delete', list_path(list.id), method: :delete, data: { confirm: 'Are you sure?'} %>
  <br>
  <% end %>

  <br>

  <a href="/lists/new">Create New List</a>

todo/app/views/lists/new.erb
<h3>Create A New List</h3>

<%= render partial: 'form', locals: {list: @list}%>

todo/app/views/tasks/_form.erb
<%= form_for [list, task] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, value: task.title %>
  <%= f.submit %>
<%end%>

todo/app/views/tasks/index.erb
<h3><%=@list.name%></h3>

<% @list.tasks.each do |task| %>
  <%= "[#{task.completed ? X : ' '}] #{task.title}" %>
  <br>
<%end%>

<br>
<%= link_to 'Add Task', new_list_task_path(@list)%>

todo/app/views/tasks/new.erb
<h3>Create A New Task For This List</h3>

<%= render partial: 'form', locals: {task: @task, list: @list} %>